import { Metadata } from "next";

import { plusJakartaSansFont, robotoMono } from "@/app/fonts";
import Navbar from "@/components/Navbar";
import { SocketProvider } from "@/lib/socket-context";

import "./globals.css";

export const metadata: Metadata = {
  title: "Gamba App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSansFont.variable} ${robotoMono.variable} antialiased`}
      >
        <SocketProvider>
          <div className="min-h-screen font-main">
            <Navbar />
            {children}
          </div>
        </SocketProvider>
      </body>
    </html>
  );
}
