import { SocketProvider } from "@/lib/socket-context";

import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Roboto_Mono } from "next/font/google";

import "./globals.css";

const plusJakartaSansFont = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["600", "800"],
  variable: "--font-plus-jakarta-sans",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Gamba App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSansFont.variable} ${robotoMono.variable} antialiased`}
      >
        <SocketProvider>
          <div className="font-main">{children}</div>
        </SocketProvider>
      </body>
    </html>
  );
}
